FIND_PATH(Readline_INCLUDE_DIRS readline.h PATHS /usr/include/readline)
FIND_LIBRARY(Readline_LIBRARIES readline) 

IF (Readline_INCLUDE_DIRS AND Readline_LIBRARIES)
   SET(Readline_FOUND TRUE)
ENDIF (Readline_INCLUDE_DIRS AND Readline_LIBRARIES)

IF (Readline_FOUND)
   IF (NOT Readline_FIND_QUIETLY)
      MESSAGE(STATUS "Found GNU readline: ${Readline_LIBRARIES}")
      MESSAGE(STATUS "Found GNU readline headers: ${Readline_INCLUDE_DIRS}")
   ENDIF (NOT Readline_FIND_QUIETLY)
ELSE (Readline_FOUND)
   IF (Readline_FIND_REQUIRED)
      IF (NOT Readline_INCLUDE_DIRS)
         MESSAGE(FATAL_ERROR "Could not find GNU readline headers!")
      ENDIF (NOT Readline_INCLUDE_DIRS)
      IF (NOT Readline_LIBRARIES)
         MESSAGE(FATAL_ERROR "Could not find GNU readline!")
      ENDIF (NOT Readline_LIBRARIES)
   ENDIF (Readline_FIND_REQUIRED)
ENDIF (Readline_FOUND)
