FIND_PATH(Libiodbc_INCLUDE_DIRS sql.h PATHS /usr/include/iodbc /usr/include/libiodbc)
FIND_LIBRARY(Libiodbc_LIBRARIES libiodbc.so)

IF (Libiodbc_INCLUDE_DIRS AND Libiodbc_LIBRARIES)
   SET(Libiodbc_FOUND TRUE)
ENDIF (Libiodbc_INCLUDE_DIRS AND Libiodbc_LIBRARIES)

IF (Libiodbc_FOUND)
   IF (NOT Libiodbc_FIND_QUIETLY)
      MESSAGE(STATUS "Found iODBC: ${Libiodbc_LIBRARIES}")
      MESSAGE(STATUS "Found iODBC headers: ${Libiodbc_INCLUDE_DIRS}")
   ENDIF (NOT Libiodbc_FIND_QUIETLY)
ELSE (Libiodbc_FOUND)
   IF (Libiodbc_FIND_REQUIRED)
      IF (NOT Libiodbc_INCLUDE_DIRS)
         MESSAGE(FATAL_ERROR "Could not find iODBC headers!")
      ENDIF (NOT Libiodbc_INCLUDE_DIRS)
      IF (NOT Libiodbc_LIBRARIES)
         MESSAGE(FATAL_ERROR "Could not find iODBC libraries!")
      ENDIF (NOT Libiodbc_LIBRARIES)
   ENDIF (Libiodbc_FIND_REQUIRED)
ENDIF (Libiodbc_FOUND)
